name: MakeMKV Wrapper
version: "1.1.0"
slug: makemkv-wrapper
description: Wraps the jlesage/docker-makemkv container as a Home Assistant add-on.
url: https://github.com/hfbauman/hass-makemkv/tree/main/makemkv-wrapper
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
boot: auto
init: false
ingress: true
ingress_port: 5800
panel_icon: mdi:disc
panel_title: MakeMKV
map:
  - config:rw
  - media:rw
  - share:rw
devices:
  - /dev/sr0
host_network: true
privileged:
  - SYS_ADMIN
  - DAC_READ_SEARCH
